name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build rustifact
      run: cargo build
    - name: Run examples
      run: for dir in examples/*; do (cd "$dir" && cargo run) done
    - name: Run tests
      run: cd test && cargo run
